### ISSUE TITLE
Can't trade in Pokemon Heart gold

### ISSUE THREAD

**Issue by zanpei** [caela/DeSmuMEaltWFC#1]
Wifi-piazza and wifi-club did not work.Is there any other way?

**Comment by caela** [comment]
No, wifi-club trade for Pokemon Gen4 is not working as written in the ChangeLog. You should use the GTS (Global Trade Station) instead. Check out which pokemon are available at http://pkmnclassic.net/gts/ Then you can trade Pokemon over the GTS (also from two local games of the same generation if you start your DeSmuME twice, just make sure only one is connected to the server at the same time, or you can use two different computers).
